name: publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node 8
        uses: actions/setup-node@v1
        with:
          node-version: 8
          registry-url: 'https://registry.npmjs.org'
      - name: Install package dependencies
        run: npm ci
      - name: Build project
        run: npm run compile
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}